language: node_js
node_js:
  - 8.0
env:
  global:
    - MONGODB_URI=mongodb://localhost:27017/yeep
    - JWT_SECRET="keep it safe, keep it hidden!"
    - STORAGE_TYPE="fs"
    - NODE_ENV=development
    - BASE_URL="https://test.yeep.app/"
  matrix:
    - MONGODB=4.0.0
before_install:
  - npm i -g npm@latest
install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork --replSet cosmos
  - sleep 20
  - mongo --eval 'rs.initiate()'
  - npm ci
  - npm run migrate up
  - npm run mkdir:uploads -- -m 666
after_script:
  - pkill mongod
